#!/usr/bin/env fish

set PERCENTAGE (pmset -g batt | grep --extended-regexp --only-matching '\d+%' | cut -d % -f 1)
set CHARGING (pmset -g batt | grep 'AC Power')

if [ $CHARGING ]
    set ICON 
else
    switch $PERCENTAGE
        case (seq 90 100)
            set ICON 
        case (seq 60 89)
            set ICON 
        case (seq 30 59)
            set ICON 
        case (seq 10 29)
            set ICON 
        case (seq 0 9)
            set ICON 
    end
end

# The item invoking this script (name $NAME) will get its icon and label
# updated with the current battery status
sketchybar --set $NAME icon=$ICON label=$PERCENTAGE%
