#!/usr/bin/env fish

# The volume_change event supplies a $INFO variable in which the current volume
# percentage is passed to the script.

if [ $SENDER = volume_change ]
    set VOLUME $INFO

    switch $VOLUME
        case (seq 60 100)
            set ICON 󰕾
        case (seq 30 59)
            set ICON 󰖀
        case (seq 1 29)
            set ICON 󰕿
        case 0
            set ICON 󰖁
    end

    sketchybar --set $NAME icon=$ICON label=$VOLUME%
end
