accordion-padding = 20
on-focus-changed = ['move-mouse window-lazy-center']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
start-at-login = true

[exec.env-vars]
# The Aerospace executable is located in `/opt/homebrew/bin,` and my custom
# script is symlinked to `/usr/local/bin.`
PATH = '/opt/homebrew/bin:/usr/local/bin:${PATH}'

[mode.main.binding]
# https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
cmd-alt-h = []

# Window focus.
alt-h = 'focus left --boundaries-action stop'
alt-j = 'focus down --boundaries-action stop'
alt-k = 'focus up --boundaries-action stop'
alt-l = 'focus right --boundaries-action stop'

# Window movement.
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspace focus.
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# Window movement between workspaces.
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# Monitor focus.
alt-ctrl-cmd-1 = 'focus-monitor 1'
alt-ctrl-cmd-2 = 'focus-monitor 2'

# Window movement between monitors.
alt-ctrl-cmd-shift-1 = ['move-node-to-monitor 1', 'focus-monitor 1']
alt-ctrl-cmd-shift-2 = ['move-node-to-monitor 2', 'focus-monitor 2']

# App focus cycling.
alt-enter = 'exec-and-forget cycle-app-windows kitty'
alt-ctrl-cmd-enter = 'exec-and-forget cycle-app-windows kitty'

alt-ctrl-cmd-c = "exec-and-forget cycle-app-windows 'Docker Desktop'"           # 'c' as in 'container'.
alt-ctrl-cmd-d = 'exec-and-forget cycle-app-windows DBeaver'
alt-ctrl-cmd-f = 'exec-and-forget cycle-app-windows Finder'
alt-ctrl-cmd-g = "exec-and-forget cycle-app-windows 'Google Chrome'"
alt-ctrl-cmd-i = "exec-and-forget cycle-app-windows 'IntelliJ IDEA CE'"
alt-ctrl-cmd-m = "exec-and-forget cycle-app-windows 'MuseScore 4'"
alt-ctrl-cmd-n = 'exec-and-forget cycle-app-windows Notion'
alt-ctrl-cmd-o = "exec-and-forget cycle-app-windows 'Microsoft Outlook'"
alt-ctrl-cmd-p = "exec-and-forget cycle-app-windows 'Parallels Desktop'"
alt-ctrl-cmd-r = "exec-and-forget cycle-app-windows 'Microsoft Remote Desktop'"
alt-ctrl-cmd-s = "exec-and-forget cycle-app-windows 'System Settings'"
alt-ctrl-cmd-t = "exec-and-forget cycle-app-windows 'Microsoft Teams'"
alt-ctrl-cmd-v = "exec-and-forget cycle-app-windows 'Visual Studio Code'"
alt-ctrl-cmd-z = 'exec-and-forget cycle-app-windows zoom.us'

# Workspace switching.
alt-tab = 'workspace-back-and-forth'

alt-backtick = 'mode service'

[mode.service.binding]
v = ["exec-and-forget reconnect-vpn 'ICT VPN'", 'mode main']

# Layout switching.
slash = ['layout tiles horizontal vertical', 'mode main']
comma = ['layout accordion horizontal vertical', 'mode main']

# Window resizing.
minus = 'resize smart -50'
equal = 'resize smart +50'
0 = 'balance-sizes'

esc = ['reload-config', 'mode main']

[workspace-to-monitor-force-assignment]
# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 2
7 = 2
8 = 2
9 = 2
10 = 2
