format = """
[░▒▓](foreground)\
$os\
[](fg:foreground bg:pink)\
$username\
[](fg:pink bg:red)\
$directory\
[](fg:red bg:orange)\
$git_branch\
$git_status\
[](fg:orange bg:cyan)\
$nodejs\
[](fg:cyan bg:purple)\
$docker_context\
[](fg:purple bg:comment)\
$time\
[ ](fg:comment)\
"""

palette = 'dracula'

[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
selection = '#44475a'
foreground = '#f8f8f2'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

[os]
disabled = false
format = '[ $symbol ]($style)'
style = "bg:foreground fg:background"
symbols = { Macos = "" }

[username]
format = '[ $user ]($style)'
show_always = true
style_user = "bg:pink"

[directory]
format = "[ $path ]($style)"
style = "bg:red"
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
format = '[ $symbol $branch ]($style)'
style = "bg:orange"
symbol = ""

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bg:orange"

[nodejs]
format = '[ $symbol ($version) ]($style)'
style = "bg:cyan"
symbol = ""

[docker_context]
format = '[ $symbol $context ]($style) $path'
style = "bg:purple"
symbol = " "

[time]
disabled = false
format = '[ 󰥔 $time ]($style)'
style = "bg:comment"
time_format = "%R"
