#!/usr/bin/zsh

# Based on the default config in `/etc/X11/xinit/xinitrc`.
# https://wiki.archlinux.org/title/Xinit#xinitrc

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Enable numlock.
numlockx &

# Load picom compositor in the background.
picom --daemon

# Load xbanish in the background.
# Xmonad is responsible for moving the cursor out of the way.
xbanish -i control -i shift &

# Load xmonad tiling window manager with dbus enabled.
# https://xmonad.org/INSTALL.html#dont-recompile-on-every-startup
# https://wiki.archlinux.org/title/xmonad#Problems_with_finding_shared_libraries_after_update
# https://bbs.archlinux.org/viewtopic.php?id=193851
exec dbus-launch $XDG_CACHE_HOME/xmonad/xmonad-x86_64-linux
