#!/bin/sh

# Based on `/etc/X11/xinit/xinitrc`.
# https://wiki.archlinux.org/title/Xinit#xinitrc

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Map Caps Lock to Escape.
# https://superuser.com/a/568573
setxkbmap eu -option caps:escape

# Load a background image using feh.
feh --no-fehbg --bg-fill '/usr/share/backgrounds/archlinux/wave.png'

# Load xbanish in the background to hide the mouse when the keyboard is used.
xbanish -m se -i all &

# Start `ssh-agent` with each X session.
# https://wiki.archlinux.org/title/SSH_keys#ssh-agent_as_a_wrapper_program
eval $(ssh-agent)

# Load xmonad tiling window manager.
# https://xmonad.org/INSTALL.html#dont-recompile-on-every-startup
# https://wiki.archlinux.org/title/xmonad#Problems_with_finding_shared_libraries_after_update
exec $XDG_CACHE_HOME/xmonad/xmonad-x86_64-linux
