git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  enlargedSideViewLocation: top
os:
  edit: "focus-neovim {{filename}}"
  editAtLine: "focus-neovim {{filename}} {{line}}"
promptToReturnFromSubprocess: false
