#!/usr/bin/env fish

yabai --message config \
    external_bar all:$SKETCHY_BAR_HEIGHT:0 \
    layout bsp \
    mouse_follows_focus on \
    window_gap 5 \
    window_origin_display focused

yabai --message rule --add app!='^(Code|Google Chrome|kitty)$' manage=off
yabai --message rule --apply
