#!/usr/bin/env fish

# https://trello.com/c/QfYFXbJ7
yabai --message signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

set --local spacing 5
yabai --message config \
    bottom_padding $spacing \
    external_bar main:20:0 \
    layout bsp \
    left_padding $spacing \
    mouse_follows_focus on \
    right_padding $spacing \
    top_padding 0 \
    window_gap $spacing \
    window_origin_display focused

yabai --message rule --add app!='^(Code|GarageBand|Google Chrome|MuseScore|kitty|Warp)$' manage=off layer=below
