#!/usr/bin/env fish

# https://trello.com/c/QfYFXbJ7


yabai --message signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

sudo yabai --load-sa

yabai --message config \
    external_bar all:35:0 \
    layout bsp \
    mouse_follows_focus on \
    window_gap 5 \
    window_origin_display focused

yabai --message rule --add app!='^(Code|GarageBand|Google Chrome|MuseScore|kitty|Warp)$' manage=off layer=below
