-- Border
vim.o.winborder = 'rounded'

-- Completion
vim.o.completeopt = 'menu,menuone,noselect'

-- Cursor
vim.o.cursorline = true
vim.opt.guicursor:append('a:blinkon100')
vim.o.updatetime = 250 -- Speed up "highlight under cursor".

-- Diagnostics
vim.diagnostic.config({
    float = { source = true },
    signs = {
        text = {
            [vim.diagnostic.severity.ERROR] = ' ',
            [vim.diagnostic.severity.HINT] = ' ',
            [vim.diagnostic.severity.INFO] = ' ',
            [vim.diagnostic.severity.WARN] = ' ',
        },
    },
})

-- Environment
-- Environment variable to speed up `:Telescope man_pages`.
-- Generated by `../../bin/makewhatis`; see the script for more information.
-- stylua: ignore start
vim.env.MANPATH = '/usr/local/share/man:/Applications/kitty.app/Contents/Resources/man:/opt/homebrew/share/man:/opt/homebrew/opt/mysql-client@8.4/share/man:/opt/homebrew/opt/curl/share/man:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man'
-- stylua: ignore end

-- Editor
vim.o.confirm = true

-- Folds
vim.o.foldenable = false
vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.wo.foldmethod = 'expr'

-- History
vim.o.undofile = true

-- Leader
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

-- Line numbers
vim.o.number = true
vim.o.relativenumber = true

-- Plugin requisites
vim.o.ruler = false
vim.o.showmode = false
vim.o.signcolumn = 'yes'

-- Search & Replace
vim.o.ignorecase = true
vim.o.inccommand = 'split'
vim.o.smartcase = true

-- Splits
vim.o.splitbelow = true
vim.o.splitright = true

-- Status line
vim.o.laststatus = 3
vim.o.winbar = '%=%f'

-- Tabs & Spaces
-- http://vimcasts.org/episodes/tabs-and-spaces/
local tab_width_in_spaces = 2
vim.o.shiftwidth = tab_width_in_spaces
vim.o.softtabstop = tab_width_in_spaces
vim.o.tabstop = tab_width_in_spaces

-- Text
vim.o.breakindent = true
vim.o.list = true
vim.opt.listchars = { nbsp = '', tab = '󰌒 ', trail = '󱁐' }
