#!/usr/bin/env bash

echo '📝 Setting up prerequisites.'
mkdir -p $HOME/.cache/
# Set the context to this script's directory with `cd`.
# https://stackoverflow.com/a/59916
cd $(dirname $0)

echo '📻 Adjusting correct directory permissions.'
# https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
chmod u=rwx,go= $(pwd)/../gnupg/

echo '📀 Initializing and fetching data for Git submodules.'
# https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
git submodule init
git submodule update

# https://stackoverflow.com/a/677212
if ! command -v brew &>/dev/null; then
	# https://brew.sh/#install
	echo '🍺 Installing Homebrew.'
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo '📦 Installing Homebrew packages.'
BREWFILE_PATH=$(pwd)/../brew/Brewfile
# https://docs.brew.sh/Manpage#bundle-subcommand
brew bundle check --file $BREWFILE_PATH || brew bundle install --file $BREWFILE_PATH

echo '📈 Running `brew doctor`.'
brew doctor

SHELLS_PATH=/etc/shells
if ! grep --quiet fish $SHELLS_PATH; then
	# https://fishshell.com/docs/current/#default-shell
	echo '🐠 Setting fish as the default shell.'
	echo $(which fish) | sudo tee -a $SHELLS_PATH
	chsh -s $(which fish)
	login $(whoami)
fi

# https://stackoverflow.com/a/677212
if ! command -v vimgolf &>/dev/null; then
	echo '⛳️ Installing VimGolf.'
	gem install vimgolf
	vimgolf setup
fi

echo '📺 Updating and (re)starting yabai and skhd services.'
YABAI_PATH=/private/etc/sudoers.d/yabai
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition
sudo rm -f $YABAI_PATH && sudo echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee -a $YABAI_PATH >/dev/null
# Set same permissions as `visudo` would.
sudo chmod ug=r,o= $YABAI_PATH
yabai --restart-service &>/dev/null || yabai --install-service &>/dev/null
skhd --restart-service &>/dev/null || skhd --install-service &>/dev/null

echo '📶 (Re)starting SketchyBar service.'
brew services restart sketchybar

echo '===================================================='
echo '💡 Remember to manually set up the following things:'
echo '🔑 GPG keys'
echo '===================================================='

if [ $TERM != 'xterm-kitty' ]; then
	echo '🐈 Opening kitty terminal.'
	open -a kitty
fi
