#!/usr/bin/env zsh

echo '📝 Setting up prerequisites.'
mkdir -p $HOME/.cache/
# Set the context to this script's directory with `cd`.
# https://stackoverflow.com/a/59916
cd $(dirname $0)

echo '📻 Adjusting correct directory permissions.'
# https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
chmod u=rwx,go= $(realpath $(pwd)/../gnupg/)

echo '🔗 Symlinking scripts.'
for script in $(realpath $(pwd)/../bin/*); do
	sudo ln -s $script /usr/local/bin/$(basename $script)
done

echo '📀 Initializing and fetching data for Git submodules.'
# https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
git submodule init
git submodule update

# https://stackoverflow.com/a/677212
if ! command -v brew &>/dev/null; then
	echo '🍺 Installing Homebrew.'
	# https://brew.sh/#install
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo '🍺 Adding Homebrew to `$PATH` during setup.'
	# https://docs.brew.sh/Manpage#shellenv-bashcshfishpwshshtcshzsh
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo '📦 Installing Homebrew packages.'
BREWFILE_PATH=$(realpath $(pwd)/../brew/Brewfile)
# https://docs.brew.sh/Manpage#bundle-subcommand
brew bundle check --file $BREWFILE_PATH || brew bundle install --file $BREWFILE_PATH

echo '📈 Running `brew doctor`.'
brew doctor

echo '📦 Installing asdf plugins.'
# Deno
asdf plugin add deno
asdf install deno latest
asdf global deno latest
# Node.js
asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest
# Ruby
asdf plugin add ruby
asdf install ruby latest
asdf global ruby latest
echo '🍺 Adding asdf plugins to `$PATH` during setup.'
# https://asdf-vm.com/guide/getting-started.html#_3-install-asdf
source $(brew --prefix asdf)/libexec/asdf.sh

echo '🎹 Downloading EurKEY keyboard layout.'
sudo curl https://raw.githubusercontent.com/alexmick/EurKEY-Mac/main/EurKEY.keylayout --remote-name --output-dir /Library/Keyboard\ Layouts/ --silent
sudo curl https://raw.githubusercontent.com/alexmick/EurKEY-Mac/main/EurKEY.icns --remote-name --output-dir /Library/Keyboard\ Layouts/ --silent

# https://stackoverflow.com/a/677212
if ! command -v vimgolf &>/dev/null; then
	echo '⛳️ Installing VimGolf.'
	gem install vimgolf
	vimgolf setup
fi

SHELLS_PATH=/etc/shells
if ! grep --quiet fish $SHELLS_PATH; then
	echo '🐠 Setting fish as the default shell.'
	# https://fishshell.com/docs/current/#default-shell
	echo $(which fish) | sudo tee -a $SHELLS_PATH
	chsh -s $(which fish)
fi

echo '📺 Updating and (re)starting yabai and skhd services.'
YABAI_PATH=/private/etc/sudoers.d/yabai
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition
sudo rm -f $YABAI_PATH && sudo echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee -a $YABAI_PATH >/dev/null
# Set same permissions as `visudo` would.
sudo chmod ug=r,o= $YABAI_PATH
yabai --restart-service &>/dev/null || yabai --install-service &>/dev/null
skhd --restart-service &>/dev/null || skhd --install-service &>/dev/null

echo '📶 (Re)starting SketchyBar service.'
brew services restart sketchybar

echo '🍫 Autohiding the Dock and increasing the animation delay.'
# https://macos-defaults.com/dock/autohide.html
defaults write com.apple.dock "autohide" -bool "true"
# https://macos-defaults.com/dock/autohide-delay.html#set-to-0
defaults write com.apple.dock "autohide-delay" -float "999"
killall Dock

echo '=================================================================='
echo '💡 Remember to manually set up and configure the following things:'
echo '🔑 GPG keys'
echo '🍎 macOS settings'
echo '=================================================================='

if [ $TERM != 'xterm-kitty' ]; then
	echo '🐈 Opening kitty terminal.'
	open -a kitty
fi
