#!/usr/bin/env bash

mkdir -p $HOME/.cache/

# https://stackoverflow.com/a/59916
cd $(dirname $0)

# https://gist.github.com/oseme-techguy/bae2e309c084d93b75a9b25f49718f85
chmod u=rwx,go= $(pwd)/../gnupg/

# https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
git submodule init
git submodule update

# https://stackoverflow.com/a/677212
if ! command -v brew &>/dev/null; then
	# https://brew.sh/#install
	echo '🍺 Installing Homebrew.'
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# https://docs.brew.sh/Manpage#bundle-subcommand
echo '📦 Installing Homebrew packages.'
BREWFILE_PATH=$(pwd)/../brew/Brewfile
brew bundle check --file $BREWFILE_PATH || brew bundle install --file $BREWFILE_PATH

SHELLS_PATH=/etc/shells
if ! grep --quiet fish $SHELLS_PATH; then
	# https://fishshell.com/docs/current/#default-shell
	echo '🐠 Setting fish as the default shell.'
	echo $(which fish) | sudo tee -a $SHELLS_PATH
	chsh -s $(which fish)
	login $(whoami)
fi

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)#configure-scripting-addition
echo '📺 Updating and (re)starting yabai and skhd services.'
YABAI_PATH=/private/etc/sudoers.d/yabai
sudo rm -f $YABAI_PATH && sudo echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee -a $YABAI_PATH >/dev/null
# Set same permissions as `visudo` would.
sudo chmod ug=r,o= $YABAI_PATH
yabai --restart-service &>/dev/null || yabai --install-service &>/dev/null
skhd --restart-service &>/dev/null || skhd --install-service &>/dev/null

if [ $TERM != 'xterm-kitty' ]; then
	echo '🐈 Opening kitty terminal.'
	open -a kitty
fi
