#!/usr/bin/env bash

mkdir -p $HOME/.cache/

# https://stackoverflow.com/a/59916
cd $(dirname $0)

# https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
git submodule init
git submodule update

# https://stackoverflow.com/a/677212
if ! command -v brew &>/dev/null; then
	# https://brew.sh/#install
	echo '🍺 Installing Homebrew.'
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# https://docs.brew.sh/Manpage#bundle-subcommand
echo '📦 Installing Homebrew packages.'
BREWFILE_PATH=$(pwd)/../brew/Brewfile
brew bundle check --file $BREWFILE_PATH || brew bundle install --file $BREWFILE_PATH

SHELLS_PATH=/etc/shells
if ! grep --quiet fish $SHELLS_PATH; then
	# https://fishshell.com/docs/current/#default-shell
	echo '🐠 Setting fish as the default shell.'
	echo $(which fish) | sudo tee -a $SHELLS_PATH
	chsh -s $(which fish)
	login $(whoami)
fi

if [ $TERM != 'xterm-kitty' ]; then
	echo '🐈 Opening kitty terminal.'
	open -a kitty
fi
