#!/usr/bin/env fish

# https://trello.com/c/hi1zvqeZ
cp /usr/local/opt/oh-my-posh/themes/dracula.omp.json $XDG_CONFIG_HOME/oh-my-posh/

# https://trello.com/c/QfYFXbJ7
cp /usr/local/opt/yabai/share/yabai/examples/yabairc $XDG_CONFIG_HOME/yabai/
cp /usr/local/opt/yabai/share/yabai/examples/skhdrc $XDG_CONFIG_HOME/skhd/
