#!/usr/bin/env fish

cd (dirname (status --current-filename))

echo '📀 Updating Git submodules.'
git submodule update --init --recursive --remote
echo '🗃️ Updating whatis databases'
makewhatis
echo '🍺 Updating Homebrew packages.'
brew update
echo '🍺 Upgrading Homebrew packages.'
brew upgrade --greedy --force
echo '🍺 Removing stale Homebrew lock files and outdated downloads.'
brew cleanup
echo '🍺 Removing unused Homebrew dependencies.'
brew autoremove
echo '🍺 Updating Brewfile.'
# https://trello.com/c/46kxNqE9
cd $XDG_CONFIG_HOME/brew/
brew bundle dump --force
