#!/usr/bin/env fish

# https://trello.com/c/hi1zvqeZ
cp /usr/local/opt/oh-my-posh/themes/dracula.omp.json (path resolve (status dirname)/../oh-my-posh/)

# https://trello.com/c/QfYFXbJ7
cp /usr/local/opt/yabai/share/yabai/examples/yabairc (path resolve (status dirname)/../yabai/)
cp /usr/local/opt/yabai/share/yabai/examples/skhdrc (path resolve (status dirname)/../skhd/)
